version: 0.0
resources:
  - myReactAppService: 
      type: AWS::ECS::Service
      properties:
        taskDefinition: "myReactAppTaskDef"
        loadBalancerInfo:
          containerName: "my-react-app-container"
          containerPort: 90
hooks:
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
