version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum update -y
      - amazon-linux-extras install docker
      - service docker start
      - docker --version
      - echo Docker installed.
  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 713881792798.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=713881792798.dkr.ecr.us-east-1.amazonaws.com/my-react-app
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo REPOSITORY_URI=$REPOSITORY_URI
      - echo IMAGE_TAG=$IMAGE_TAG
  
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Build completed.
  
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Docker image pushed to $REPOSITORY_URI:$IMAGE_TAG
  
artifacts:
  files:
    - appspec.yml
    - taskdef.json
