name: Backup to S3

on:
  push:
    branches:
      - main  # or any branch you want to back up

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIA2MNVLWEPOI4QNBMU
        aws-secret-access-key: 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
        aws-region: us-east-1

    # Step 3: Sync repository to S3
    - name: Sync repository to S3
      run: |
        aws s3 sync . s3://anshul-github-backup/ --exclude ".git/*" --delete
